### ISSUE TITLE
Editing all control box commands

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#17] opened 2015-09-21 15:24 UTC
I like being able to edit the content and order of the commands in the control box. Can the control.xml file contain all of the control box commands? Currently, the pause, speak, and copy commands are programmed elsewhere so they are uneditable.

**Comment by ipomoena** [comment] 2015-09-21 15:44
duplicate of https://github.com/ipomoena/dasher/issues/11

**Closed by ipomoena** 2015-09-21 15:44 UTC
